# Generated by Django 4.1.13 on 2024-02-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=20)),
                ('languages', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=500)),
                ('tags', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10000)),
                ('insertTime', models.DateTimeField()),
            ],
        ),
    ]
